# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gitDemo

  target 'gitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
